binary_sensor:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms0
    status_balancing:
      name: "${bms_name} status balancing"
    status_precharging:
      name: "${bms_name} status precharging"      
    status_charging:
      name: "${bms_name} status charging"
    status_discharging:
      name: "${bms_name} status discharging"
    status_online:
      name: "${bms_name} status online"
    status_heating:
      name: "${bms_name} status heating"      
    # alarm_wireres:
    #   name: "${bms_name} alarm WireRes"
    # alarm_mosotp:
    #   name: "${bms_name} alarm MosOTP"
    # alarm_cellquantity:
    #   name: "${bms_name} alarm CellQuantity"
    # alarm_cursensorerr:
    #   name: "${bms_name} alarm CurSensorErr"
    # alarm_cellovp:
    #   name: "${bms_name} alarm CellOVP"
    # alarm_batovp:
    #   name: "${bms_name} alarm BatOVP"
    # alarm_chocp:
    #   name: "${bms_name} alarm ChOCP"
    # alarm_chscp:
    #   name: "${bms_name} alarm ChSCP"
    # alarm_chotp:
    #   name: "${bms_name} alarm ChOTP"
    # alarm_chutp:
    #   name: "${bms_name} alarm ChUTP"
    # alarm_cpuauxcommuerr:
    #   name: "${bms_name} alarm CPUAuxCommuErr"
    # alarm_celluvp:
    #   name: "${bms_name} alarm CellUVP"
    # alarm_batuvp:
    #   name: "${bms_name} alarm BatUVP"
    # alarm_dchocp:
    #   name: "${bms_name} alarm DchOCP"
    # alarm_dchscp:
    #   name: "${bms_name} alarm DchSCP"
    # alarm_dchotp:
    #   name: "${bms_name} alarm DchOTP"
    # alarm_chargemos:
    #   name: "${bms_name} alarm ChargeMOS"
    # alarm_dischargemos:
    #   name: "${bms_name} alarm DischargeMOS"
    # alarm_gpsdisconneted:
    #   name: "${bms_name} alarm GPSDisconneted"
    # alarm_modifypwdintime:
    #   name: "${bms_name} alarm ModifyPWDinTime"
    # alarm_dischargeonfailed:
    #   name: "${bms_name} alarm DischargeOnFailed"
    # alarm_batteryovertemp:
    #   name: "${bms_name} alarm BatteryOverTemp"
    # alarm_temperaturesensoranomaly:
    #   name: "${bms_name} alarm TemperatureSensorAnomaly"
    # alarm_plcmoduleanomaly:
    #   name: "${bms_name} alarm PLCModuleAnomaly"
    # alarm_mostempsensorabsent:
    #   name: "${bms_name} alarm MOSTempSensorAbsent"
    # alarm_battempsensor1absent:
    #   name: "${bms_name} alarm BATTempSensor1Absent"
    # alarm_battempsensor2absent:
    #   name: "${bms_name} alarm BATTempSensor2Absent"
    # alarm_battempsensor3absent:
    #   name: "${bms_name} alarm BATTempSensor3Absent"
    # alarm_battempsensor4absent:
    #   name: "${bms_name} alarm BATTempSensor4Absent"
    # alarm_battempsensor5absent:
    #   name: "${bms_name} alarm BATTempSensor5Absent"

sensor:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms0
    balancing_direction:
      name: "${bms_name} balancing direction"
    cell_voltage_min:
      name: "${bms_name} cell voltage min"
    cell_voltage_max:
      name: "${bms_name} cell voltage max"
    cell_voltage_min_cell_number:
      name: "${bms_name} cell voltage min cell number"
    cell_voltage_max_cell_number:
      name: "${bms_name} cell voltage max cell number"
    cell_delta_voltage:
      name: "${bms_name} cell delta voltage"
    cell_average_voltage:
      name: "${bms_name} cell average voltage"
    cell_resistance_min:
      name: "${bms_name} cell resistance min"
    cell_resistance_max:
      name: "${bms_name} cell resistance max"      
    cell_resistance_min_cell_number:
      name: "${bms_name} cell resistance min cell number"
    cell_resistance_max_cell_number:
      name: "${bms_name} cell resistance max cell number"      
    cell_voltage_01:
      name: "${bms_name} cell voltage 01"
    cell_voltage_02:
      name: "${bms_name} cell voltage 02"
    cell_voltage_03:
      name: "${bms_name} cell voltage 03"
    cell_voltage_04:
      name: "${bms_name} cell voltage 04"
    cell_voltage_05:
      name: "${bms_name} cell voltage 05"
    cell_voltage_06:
      name: "${bms_name} cell voltage 06"
    cell_voltage_07:
      name: "${bms_name} cell voltage 07"
    cell_voltage_08:
      name: "${bms_name} cell voltage 08"
    cell_voltage_09:
      name: "${bms_name} cell voltage 09"
    cell_voltage_10:
      name: "${bms_name} cell voltage 10"
    cell_voltage_11:
      name: "${bms_name} cell voltage 11"
    cell_voltage_12:
      name: "${bms_name} cell voltage 12"
    cell_voltage_13:
      name: "${bms_name} cell voltage 13"
    cell_voltage_14:
      name: "${bms_name} cell voltage 14"
    cell_voltage_15:
      name: "${bms_name} cell voltage 15"
    cell_voltage_16:
      name: "${bms_name} cell voltage 16"
    cell_resistance_01:
      name: "${bms_name} cell resistance 01"
    cell_resistance_02:
      name: "${bms_name} cell resistance 02"
    cell_resistance_03:
      name: "${bms_name} cell resistance 03"
    cell_resistance_04:
      name: "${bms_name} cell resistance 04"
    cell_resistance_05:
      name: "${bms_name} cell resistance 05"
    cell_resistance_06:
      name: "${bms_name} cell resistance 06"
    cell_resistance_07:
      name: "${bms_name} cell resistance 07"
    cell_resistance_08:
      name: "${bms_name} cell resistance 08"
    cell_resistance_09:
      name: "${bms_name} cell resistance 09"
    cell_resistance_10:
      name: "${bms_name} cell resistance 10"
    cell_resistance_11:
      name: "${bms_name} cell resistance 11"
    cell_resistance_12:
      name: "${bms_name} cell resistance 12"
    cell_resistance_13:
      name: "${bms_name} cell resistance 13"
    cell_resistance_14:
      name: "${bms_name} cell resistance 14"
    cell_resistance_15:
      name: "${bms_name} cell resistance 15"
    cell_resistance_16:
      name: "${bms_name} cell resistance 16"
    battery_voltage:
      name: "${bms_name} battery voltage"
    battery_current:
      name: "${bms_name} battery current"
    battery_power:
      name: "${bms_name} battery power"
    battery_power_charging:
      name: "${bms_name} battery power charging"
    battery_power_discharging:
      name: "${bms_name} battery power discharging"
    temperature_sensor_1:
      name: "${bms_name} temperature sensor 1"
    temperature_sensor_2:
      name: "${bms_name} temperature sensor 2"
    temperature_sensor_3:
      name: "${bms_name} temperature sensor 3"
    temperature_sensor_4:
      name: "${bms_name} temperature sensor 4"
    temperature_sensor_5:
      name: "${bms_name} temperature sensor 5"
    temperature_powertube:
      name: "${bms_name} temperature powertube"
    battery_capacity_state_of_charge:
      name: "${bms_name} battery capacity state of charge"
    battery_capacity_remaining:
      name: "${bms_name} battery capacity remaining"
    charging_cycles:
      name: "${bms_name} charging cycles"
    battery_capacity_total_charging_cycle:
      name: "${bms_name} battery capacity total charging cycle"
    battery_total_runtime:
      name: "${bms_name} battery total runtime"
    balancing_current:
      name: "${bms_name} balancing current"
    errors_bitmask:
      name: "${bms_name} errors bitmask"
    cell_count_real:
      name: "${bms_name} cell count real"                                                       
    smart_sleep_time:
      name: "${bms_name} smart sleep time"                              
    powertube_temperature_protection:
      name: "${bms_name} powertube temperature protection" 
    powertube_temperature_protection_recovery:
      name: "${bms_name} powertube temperature protection recovery"  
    battery_total_alarms_count:     
      name: "${bms_name} battery total alarms count"  
    battery_total_alarms_active:     
      name: "${bms_name} battery total alarms active"  
    emergency_time_countdown:
      name: "${bms_name} emergency time countdown"      
    uart1_protocol_number:
      name: "${bms_name} uart1 protocol number"
    uart2_protocol_number:
      name: "${bms_name} uart2 protocol number"  
    battery_soh_valuation:    
      name: "${bms_name} battery soh valuation"
    # discharging_overcurrent_protection_release_time:    
    #   name: "${bms_name} discharging overcurrent protection release time"
    # discharging_short_circuit_protection_release_time:    
    #   name: "${bms_name} discharging short circuit protection release time"
    # charging_overcurrent_protection_release_time:    
    #   name: "${bms_name} charging overcurrent protection release time"
    # charging_short_circuit_protection_release_time:    
    #   name: "${bms_name} charging short circuit protection release time"
    # cell_undervoltage_protection_release_time:    
    #   name: "${bms_name} cell undervoltage protection release time"
    # cell_overvoltage_protection_release_time:    
    #   name: "${bms_name} cell overvoltage protection release time"

switch:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms0
    precharging:
      name: "${bms_name} precharging"
    charging:
      name: "${bms_name} charging"
    discharging:
      name: "${bms_name} discharging"
    balancing:
      name: "${bms_name} balancing"
    emergency:
      name: "${bms_name} emergency"
    heating:
      name: "${bms_name} heating"
    display_always_on:
      name: "${bms_name} display_always_on"
    charging_float_mode:
      name: "${bms_name} charging float mode"
    timed_stored_data:
      name: "${bms_name} timed stored data"
    disable_temperature_sensors:
      name: "${bms_name} disable temperature sensors"
    smart_sleep_on:
      name: "${bms_name} smart sleep on"
    disable_pcl_module:
      name: "${bms_name} disable pcl module"
    gps_heartbeat:
      name: "${bms_name} gps heartbeat"
    port_selection:
      name: "${bms_name} port selection"
    special_charger:
      name: "${bms_name} special charger"            

text_sensor:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms0
    errors:
      name: "${bms_name} errors"
    operation_status:
      name: "${bms_name} operation status"
    battery_type:
      name: "${bms_name} battery type"

    total_runtime_formatted:
      name: "${bms_name} total runtime formatted"
    info_vendorid:
      name: "${bms_name} info vendorid"
    info_hardware_version:
      name: "${bms_name} info hardware version"
    info_software_version:
      name: "${bms_name} info software version"
    info_device_name:
      name: "${bms_name} info device name"
    info_device_password:
      name: "${bms_name} info device password"   
    network_nodes_available:
      name: "${bms_name} network nodes available"  
    info_device_serial_number:
      name: "${bms_name} info device serial number"  
    info_device_setup_passcode:
      name: "${bms_name} info device setup passcode"   

number:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms0 
    cell_smart_sleep_voltage:
      name: "${bms_name} cell smart sleep voltage"  
    cell_undervoltage_protection:
      name: "${bms_name} cell undervoltage protection"
    cell_undervoltage_protection_recovery:
      name: "${bms_name} cell undervoltage protection recovery" 
    cell_overvoltage_protection:
      name: "${bms_name} cell overvoltage protection"
    cell_overvoltage_protection_recovery:
      name: "${bms_name} cell overvoltage protection recovery"
    cell_balancing_trigger_voltage:
      name: "${bms_name} cell balancing trigger voltage" 
    cell_soc100_voltage:
      name: "${bms_name} cell soc100 voltage" 
    cell_soc0_voltage:
      name: "${bms_name} cell soc0 voltage"    
    cell_request_charge_voltage:
      name: "${bms_name} cell request charge voltage"          
    cell_request_float_voltage:
      name: "${bms_name} cell request float voltage"   
    cell_power_off_voltage:
      name: "${bms_name} cell power off voltage"  
    cell_balancing_starting_voltage:
      name: "${bms_name} cell balancing starting voltage"        
    max_charging_current:
      name: "${bms_name} max charging current"          
    charging_overcurrent_protection_delay:
      name: "${bms_name} charging overcurrent protection delay"
    charging_overcurrent_protection_recovery_delay:
      name: "${bms_name} charging overcurrent protection recovery delay"
    max_discharging_current:
      name: "${bms_name} max discharging current"     
    discharging_overcurrent_protection_delay:
      name: "${bms_name} discharging overcurrent protection delay"
    discharging_overcurrent_protection_recovery_delay:
      name: "${bms_name} discharging overcurrent protection recovery delay"
    short_circuit_protection_delay:
      name: "${bms_name} short circuit protection delay"        
    short_circuit_protection_recovery_delay:
      name: "${bms_name} short circuit protection recovery delay" 
    max_balancing_current:
      name: "${bms_name} max balancing current" 
    charging_overtemperature_protection:
      name: "${bms_name} charging overtemperature protection"
    charging_overtemperature_protection_recovery:
      name: "${bms_name} charging overtemperature protection recovery"
    discharging_overtemperature_protection:
      name: "${bms_name} discharging overtemperature protection"
    discharging_overtemperature_protection_recovery:
      name: "${bms_name} discharging overtemperature protection recovery" 
    charging_lowtemperature_protection:
      name: "${bms_name} charging lowtemperature protection"
    charging_lowtemperature_protection_recovery:
      name: "${bms_name} charging lowtemperature protection recovery"
    mos_overtemperature_protection:
      name: "${bms_name} mos overtemperature protection"
    mos_overtemperature_protection_recovery:
      name: "${bms_name} mos overtemperature protection recovery"   
    cell_count_settings:
      name: "${bms_name} cell count settings"      
    battery_capacity_total_settings:
      name: "${bms_name} battery capacity total settings"            
    precharging_time_from_discharge:
      name: "${bms_name} precharging time from discharge"
    cell_request_charge_voltage_time:
      name: "${bms_name} cell request charge voltage time" 
    cell_request_float_voltage_time:
      name: "${bms_name} cell request float voltage time"       