esphome:
  name: esphome-web-278258
  friendly_name: syssi_proxy
  min_version: 2024.6.0
  name_add_mac_suffix: false

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "syssi_proxy Fallback Hotspot"
    password: "fJkEIVMYQnYE"

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

logger:
  level: INFO

external_components:
  - source: github://syssi/esphome-jk-bms@2.1.0
    refresh: 0s

packages:
  remote_package_files:
    url: https://github.com/dct-leni/syssi_proxy
    files: [smg_ii_sensors.yaml, jk_bms_sensors.yaml]  # optional; if not specified, all files will be included
    ref: main  # optional
    refresh: 0s

substitutions:
  name: combined_device
  smg_tx_pin: GPIO02
  smg_rx_pin: GPIO03
  bms_tx_pin: GPIO05
  bms_rx_pin: GPIO06

time:
  - platform: sntp

# UART for SMG-II
uart:
  - id: uart_smg
    baud_rate: 9600
    tx_pin: ${smg_tx_pin}
    rx_pin: ${smg_rx_pin}

# UART for JK-BMS
  - id: uart_bms
    baud_rate: 115200
    rx_buffer_size: 384
    tx_pin: ${bms_tx_pin}
    rx_pin: ${bms_rx_pin}

jk_modbus:
  - id: bms0
    uart_id: uart_bms
    rx_timeout: 50ms

jk_bms:
  - id: bms0
    jk_modbus_id: bms0
    update_interval: 5s

modbus:
  - id: modbus_smg
    uart_id: uart_smg
    send_wait_time: 200ms

modbus_controller:
  - id: smg0
    address: 0x01
    modbus_id: modbus_smg
    setup_priority: -10
    command_throttle: 200ms
    update_interval: 10s