esphome:
  name: "syssi-collector"
  friendly_name: syssi_collector
  min_version: 2024.6.0
  name_add_mac_suffix: false

substitutions:
  name: syssi_collector
  smg_tx_pin: GPIO02
  smg_rx_pin: GPIO03
  bms_tx_pin: GPIO05
  bms_rx_pin: GPIO06

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "syssi_collector Fallback Hotspot"
    password: "fJkEIVMYQnYE"

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

logger:
  level: INFO

external_components:
  - source: github://syssi/esphome-jk-bms@main
    refresh: 0s

packages:
  remote_package_files:
    url: https://github.com/dct-leni/syssi_collector
    files: 
      - smg_ii_sensors.yaml
      - jk_bms_sensors.yaml
    ref: main  # optional
    refresh: 0s

time:
  - platform: sntp

# UART for SMG-II
uart:
  - id: uart_smg
    baud_rate: 9600
    tx_pin: ${smg_tx_pin}
    rx_pin: ${smg_rx_pin}

# UART for JK-BMS
  - id: uart_bms
    baud_rate: 115200
    rx_buffer_size: 384
    tx_pin: ${bms_tx_pin}
    rx_pin: ${bms_rx_pin}

modbus:
  - id: modbus_bms
    uart_id: uart_bms
    flow_control_pin: GPIO12
  - id: modbus_smg
    uart_id: uart_smg
    send_wait_time: 200ms

modbus_controller:
  - id: bms0
    # Dip switch configuration of a single pack setup / address 0x01
    #  1    2    4    5
    #  on, off, off, off (0x01)
    #
    # Don't turn off all dip switches / don't use device address 0x00.
    # This is the Modbus Master mode. You must select a device address
    # between 0x01 and 0x0f so the BMS acts as Modbus Slave.
    address: 0x01
    modbus_id: modbus_bms
    setup_priority: -10
    update_interval: 5s
    command_throttle: 50ms
  - id: smg0
    address: 0x01
    modbus_id: modbus_smg
    command_throttle: 200ms
    update_interval: 10s

# <<: !include jk_bms_sensors.yaml
# <<: !include smg_ii_sensors.yaml